// import React, { useEffect } from "react";
// import logo from "../assets/images/Truerize_Logo.png";

// function Terms() {
//   useEffect(() => {
//     document.body.classList.add("info-page");
//     return () => {
//       document.body.classList.remove("info-page");
//     };
//   }, []);

//   return (
//     <div
//       style={{
//         minHeight: "100vh",
//         backgroundColor: "#ffffff", // white background
//         color: "white", // black text
//         padding: "20px 40px",
//       }}
//     >
//       {/* Header Section */}
//       <div
//         style={{
//           display: "flex",
//           alignItems: "center",
//           justifyContent: "center",
//           position: "relative",
//           marginBottom: "40px",
//         }}
//       >
//         {/* Logo on Left - Clickable */}
//         <img
//           src={logo}
//           alt="Logo"
//           style={{
//             position: "absolute",
//             left: "0",
//             height: "100px",
//             width: "auto",
//             cursor: "pointer",
//           }}
//           onClick={() => (window.location.href = "/")}
//         />

//         {/* Title at Center */}
//         <h1 style={{ fontSize: "3rem", margin: 0, textAlign: "center",color:"black" }}>
//           📑 Terms and Conditions
//         </h1>
//       </div>

//       {/* Content Section */}
//       <div
//         style={{
//           maxWidth: "1000px",
//           margin: "0 auto",
//           backgroundColor: "#360bf7ff", // light grey box for readability
//           padding: "30px",
//           borderRadius: "10px",
//           fontSize: "1.2rem",
//           lineHeight: "2",
//           boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
//         }}
//       >
//         <p style={{ marginBottom: "20px" }}>
//           Welcome to Truerize Exam Portal. By accessing and using our services,
//           you agree to the following terms and conditions:
//         </p>

//         <ol style={{ paddingLeft: "25px" }}>
//           <li>
//             By registering and accessing Truerize Exam Portal, you agree to comply
//             with all Terms & Conditions.
//           </li>
//           <li>
//             Only registered candidates with valid credentials can access exams
//             and must keep login details secure.
//           </li>
//           <li>
//             The portal is strictly for online exams; tampering, hacking, or
//             unauthorized use is prohibited.
//           </li>
//           <li>
//             Candidates must follow exam rules, avoid unfair means, and comply
//             with proctoring requirements.
//           </li>
//           <li>
//             Users must ensure stable internet and compatible devices; Truerize is
//             not liable for disruptions.
//           </li>
//           <li>
//             Personal and exam data are collected per Privacy Policy, shared only
//             with institutions/employers.
//           </li>
//           <li>
//             All exam content is intellectual property; copying, sharing, or
//             reproducing it is strictly forbidden.
//           </li>
//           <li>
//             Exam results are generated by the system/institution, and final
//             decisions rest with the employer/institution.
//           </li>
//           <li>
//             Truerize provides the platform “as is” and is not liable for data
//             loss, connectivity, or technical failures.
//           </li>
//           <li>
//             Access may be suspended or terminated for violations; terms may be
//             updated and governed by applicable law.
//           </li>
//         </ol>

//         <p style={{ marginTop: "20px" }}>
//           For questions, contact{" "}
//           <a href="mailto:support@truerize.com" style={{ color: "#3a0d5d" ,color:"white" }}>
//             support@truerize.com
//           </a>
//         </p>
//       </div>

//       {/* Back Button */}
//       <div style={{ textAlign: "center" }}>
//         <button
//           style={{
//             marginTop: "40px",
//             padding: "15px 40px",
//             backgroundColor: "#3a5bd8", // blue button
//             border: "none",
//             borderRadius: "8px",
//             color: "white",
//             fontSize: "1.3rem",
//             fontWeight: "bold",
//             cursor: "pointer",
//           }}
//           onClick={() => (window.location.href = "/")}
//         >
//           Accept
//         </button>
//       </div>
//     </div>
//   );
// }

// export default Terms;


import React, { useEffect } from "react";
import logo from "../assets/images/Truerize_Logo.png";

function Terms() {
  useEffect(() => {
    document.body.classList.add("info-page");
    return () => {
      document.body.classList.remove("info-page");
    };
  }, []);

  return (
    <div
      style={{
        minHeight: "100vh",
        backgroundColor: "#ffffff",
        color: "white",
        padding: "20px 40px",
      }}
    >
      {/* Header Section */}
      <div
        style={{
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          position: "relative",
          marginBottom: "40px",
        }}
      >
        <img
          src={logo}
          alt="Logo"
          style={{
            position: "absolute",
            left: "0",
            height: "100px",
            width: "auto",
            cursor: "pointer",
          }}
          onClick={() => (window.location.href = "/")}
        />

        <h1 style={{ fontSize: "3rem", margin: 0, textAlign: "center", color: "black" }}>
          📑 Terms and Conditions
        </h1>
      </div>

      {/* Content Section */}
      <div
        style={{
          maxWidth: "1000px",
          margin: "0 auto",
          backgroundColor: "#360bf7ff",
          padding: "30px",
          borderRadius: "10px",
          fontSize: "1.2rem",
          lineHeight: "2",
          boxShadow: "0 4px 10px rgba(0, 0, 0, 0.1)",
        }}
      >
        <p style={{ marginBottom: "20px" }}>
          Welcome to the Truerize Exam Portal. By accessing or using our services, you agree to the following terms and conditions:
        </p>

<ul style={{ paddingLeft: "25px", listStyleType: "disc", color: "white" }}>
  <li>All users must adhere to the Terms & Conditions outlined herein when using the Truerize Exam Portal.</li>
  <li>Only registered candidates with valid credentials are authorized to access exams. Users must maintain the confidentiality of their login credentials.</li>
  <li>The platform is intended solely for online assessments. Any form of tampering, unauthorized access, or malicious activity is strictly prohibited.</li>
  <li>Candidates are expected to follow exam instructions, comply with proctoring requirements, and refrain from unfair practices.</li>
  <li>Users must ensure reliable internet connectivity and compatible devices. Truerize is not responsible for disruptions due to technical limitations.</li>
  <li>Personal and exam-related data are collected and managed in accordance with our Privacy Policy and shared only with authorized institutions or employers.</li>
  <li>All exam content is the intellectual property of Truerize. Copying, sharing, or reproducing content without authorization is strictly prohibited.</li>
  <li>Exam results are system-generated and may be reviewed by the corresponding institution or employer, who holds the final authority on decisions.</li>
  <li>Truerize provides the platform "as is" and is not liable for data loss, connectivity issues, or technical failures during use.</li>
  <li>Access may be suspended or revoked for violations of these terms. Truerize reserves the right to update these Terms & Conditions in accordance with applicable laws.</li>
</ul>


        <p style={{ marginTop: "20px" }}>
          For any questions or clarifications, please contact{" "}
          <a href="mailto:support@truerize.com" style={{ color: "white" }}>
            support@truerize.com
          </a>
        </p>
      </div>

      {/* Back Button */}
      <div style={{ textAlign: "center" }}>
        <button
          style={{
            marginTop: "40px",
            padding: "15px 40px",
            backgroundColor: "#3a5bd8",
            border: "none",
            borderRadius: "8px",
            color: "white",
            fontSize: "1.3rem",
            fontWeight: "bold",
            cursor: "pointer",
          }}
          onClick={() => (window.location.href = "/")}
        >
          Accept
        </button>
      </div>
    </div>
  );
}

export default Terms;
